[package]
name = "ig-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = "0.14.0"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0.140"
tl = "0.7.8"
tokio = {version = "1.45.0", features = ["full"] }
